import fs from 'node:fs/promises';
const bases=JSON.parse(await fs.readFile('../catalogo-growth/produtos-base.json','utf8'));
const files=await fs.readdir('../catalogo-growth/detalhes');const details=new Map();for(const f of files){const d=JSON.parse(await fs.readFile('../catalogo-growth/detalhes/'+f,'utf8'));details.set(d.listingId,d)}
const money=(t,last=false)=>{const all=[...(t||'').matchAll(/R\$\s*([\d.]+,\d{2})/g)];const m=last?all.at(-1):all[0];return m?Math.round(Number(m[1].replaceAll('.','').replace(',','.'))*100):null};
const mapped=new Map();for(const filename of ['assets.json','mobile-assets.json']){const b=JSON.parse(await fs.readFile('reference/'+filename,'utf8'));for(const a of b.assets){const ext=a.path.match(/\.[a-z0-9]+$/i)?.[0]||'';mapped.set(a.url,'/assets/'+a.id+ext)}}
const products=bases.map(p=>{const d=details.get(p.id)||{};const observations=[d,...(d.observations||[]).map(o=>o.data)];const groups=[];for(const obs of observations)for(const g of obs.groups||[]){if(!g.options?.length)continue;const existing=groups.find(x=>x.name===g.name);const opts=g.options.filter(o=>o.name&&!/selecione/i.test(o.name)).map(o=>({...o,price:money(o.text,true),images:(o.images||[]).map(u=>mapped.get(u)||u)}));if(!existing)groups.push({name:g.name||'Opção',options:opts});else for(const o of opts)if(!existing.options.some(a=>a.name===o.name))existing.options.push(o)}
const price=money(d.prices?.find(x=>x.label==='Preço à vista')?.text)??money(p.text?.split('Preço à vista:')[1]);const original=money(d.prices?.find(x=>x.label==='Preço original')?.text)??money(p.text?.split('Preço original:')[1]);
const pictures=[...(p.images||[]).map(i=>i.url),...(d.gallery||[]),...(d.images||[]).filter(u=>/\/imagem\/|mockup/i.test(u)&&!u.endsWith('.svg'))];
return {id:p.id,name:p.name,path:new URL(p.url).pathname,source:p.url,price,original,images:[...new Set(pictures)].map(u=>mapped.get(u)||u),groups,category:d.breadcrumbs?.slice(1,-1).map(c=>c.name).join(' / ')||'',categoryPaths:d.breadcrumbs?.slice(1,-1).map(c=>{try{return new URL(c.url).pathname}catch{return ''}})||[],summary:d.summary||'',description:d.description||'',tables:d.tables||[],status:d.status||'pending',available:d.name&&!/ESGOTADO|AVISE.ME|INDISPONÍVEL/i.test(d.summary?.slice(0,800)||''),variantPending:!!(d.controls?.length&&!groups.length),collectedAt:d.collectedAt||null};});
const listings=JSON.parse(await fs.readFile('../catalogo-growth/listagens.json','utf8'));const collections={};for(const l of listings){const path=new URL(l.url).pathname.replace(/\/$/,'');collections[path]??={title:(l.title||path).split('|')[0].trim(),ids:[]};for(const row of l.products||[]){if(!collections[path].ids.includes(row.id))collections[path].ids.push(row.id);const p=products.find(p=>p.id===row.id);if(p&&!p.categoryPaths.includes(path))p.categoryPaths.push(path)}}

for(const parent of ['/roupas','/roupas/feminino','/roupas/masculino','/roupas/unissex','/acessorios','/snacks']){const ids=[...new Set(Object.entries(collections).filter(([k])=>k.startsWith(parent+'/')).flatMap(([,v])=>v.ids))];collections[parent]={title:parent.split('/').at(-1),ids};}
const aliases={'/c/lancamentos':'/lancamentos','/proteinas':'/proteina','/veganos':'/vegano','/vegetarianos':'/vegetariano','/termogenicos':'/termogenico','/outlet/moda':'/roupas'};for(const [a,b]of Object.entries(aliases))if(collections[b])collections[a]=collections[b];
const home=JSON.parse(await fs.readFile('reference/home-cards.json','utf8'));for(const h of home){if(products.some(p=>p.id===h.id))continue;const u=new URL(h.links[0],'https://www.gsuplementos.com.br');const path=u.searchParams.get('categoria')||u.pathname;products.push({id:h.id,name:h.name,path,source:'https://www.gsuplementos.com.br'+path,price:money(h.text.split('Preço à vista:')[1]),images:h.images.map(i=>i.url.replace('http://localhost:4173','')),groups:[],category:'',categoryPaths:['/roupas','/roupas/feminino'],status:'pending',variantPending:true,tables:[],description:''});for(const key of ['/roupas','/roupas/feminino'])collections[key].ids.push(h.id)}
for(const p of products){try{const d=JSON.parse(await fs.readFile('reference/product-snapshots/'+p.id+'.json','utf8'));p.originalPage=true;if(d.groups?.some(g=>g.options.length))p.groups=d.groups.filter(g=>g.options.length);p.variantPending=d.controls>0&&!p.groups.length;p.price=money(d.prices?.find(v=>v.label==='Preço à vista')?.text)??p.price;p.images=[...new Set([...(d.gallery||[]),...p.images])];p.status='captured'}catch{}try{await fs.access('dist/pm/'+p.id+'.html');p.mobileOriginalPage=true}catch{}}

const homepage=await fs.readFile('dist/mobile.html','utf8');const topHtml=homepage.slice(homepage.indexOf('class="vitrineTop20"'),homepage.indexOf('id="tabs-roupas"'));const topPaths=[...topHtml.matchAll(/href="([^"#]+)"/g)].map(m=>m[1].replace(/\/$/,''));const topAliases={'/100-whey-protein-concentrado-chocolate':'4074','/whey-gourmet-tiramisu':'4056','/daily-whey-morango':'4019','/daily-whey-zero-lactose-morango':'4128'};collections['/top-20']={title:'Os 20 mais vendidos',ids:[...new Set(topPaths.flatMap(path=>{const p=products.find(p=>p.path===path||p.id===topAliases[path]);return p?[p.id]:(collections[path]?.ids||[]).slice(0,1)}))]};
await fs.writeFile('dist/data/collections.json',JSON.stringify(collections));
await fs.mkdir('dist/data',{recursive:true});await fs.writeFile('dist/data/catalog.json',JSON.stringify(products));await fs.writeFile('reference/catalog-audit.json',JSON.stringify({total:products.length,withDetails:products.filter(p=>p.status!=='pending').length,pending:products.filter(p=>p.status==='pending'||p.variantPending).map(p=>({id:p.id,url:p.source}))},null,2));console.log(JSON.stringify({total:products.length,withDetails:details.size,withGroups:products.filter(p=>p.groups.length).length}));

