import fs from 'node:fs/promises';
const bases=JSON.parse(await fs.readFile('../catalogo-growth/produtos-base.json','utf8'));
const files=await fs.readdir('../catalogo-growth/detalhes');const details=new Map();for(const f of files){const d=JSON.parse(await fs.readFile('../catalogo-growth/detalhes/'+f,'utf8'));details.set(d.listingId,d)}
const money=(t,last=false)=>{const all=[...(t||'').matchAll(/R\$\s*([\d.]+,\d{2})/g)];const m=last?all.at(-1):all[0];return m?Math.round(Number(m[1].replaceAll('.','').replace(',','.'))*100):null};
const mapped=new Map();for(const filename of ['assets.json','mobile-assets.json']){const b=JSON.parse(await fs.readFile('reference/'+filename,'utf8'));for(const a of b.assets){const ext=a.path.match(/\.[a-z0-9]+$/i)?.[0]||'';mapped.set(a.url,'/assets/'+a.id+ext)}}
const products=bases.map(p=>{const d=details.get(p.id)||{};const observations=[d,...(d.observations||[]).map(o=>o.data)];const groups=[];for(const obs of observations)for(const g of obs.groups||[]){if(!g.options?.length)continue;const existing=groups.find(x=>x.name===g.name);const opts=g.options.filter(o=>o.name&&!/selecione/i.test(o.name)).map(o=>({...o,price:money(o.text,true),images:(o.images||[]).map(u=>mapped.get(u)||u)}));if(!existing)groups.push({name:g.name||'Opção',options:opts});else for(const o of opts)if(!existing.options.some(a=>a.name===o.name))existing.options.push(o)}
const price=money(d.prices?.find(x=>x.label==='Preço à vista')?.text)??money(p.text?.split('Preço à vista:')[1]);const original=money(d.prices?.find(x=>x.label==='Preço original')?.text)??money(p.text?.split('Preço original:')[1]);
const pictures=[...(p.images||[]).map(i=>i.url),...(d.gallery||[]),...(d.images||[]).filter(u=>/\/imagem\/|mockup/i.test(u)&&!u.endsWith('.svg'))];
return {id:p.id,name:p.name,path:new URL(p.url).pathname,source:p.url,price,original,images:[...new Set(pictures)].map(u=>mapped.get(u)||u),groups,category:d.breadcrumbs?.slice(1,-1).map(c=>c.name).join(' / ')||'',categoryPaths:d.breadcrumbs?.slice(1,-1).map(c=>{try{return new URL(c.url).pathname}catch{return ''}})||[],summary:d.summary||'',description:d.description||'',tables:d.tables||[],status:d.status||'pending',available:d.name&&!/ESGOTADO|AVISE.ME|INDISPONÍVEL/i.test(d.summary?.slice(0,800)||''),variantPending:!!(d.controls?.length&&!groups.length),collectedAt:d.collectedAt||null};});
await fs.mkdir('dist/data',{recursive:true});await fs.writeFile('dist/data/catalog.json',JSON.stringify(products));await fs.writeFile('reference/catalog-audit.json',JSON.stringify({total:products.length,withDetails:products.filter(p=>p.status!=='pending').length,pending:products.filter(p=>p.status==='pending'||p.variantPending).map(p=>({id:p.id,url:p.source}))},null,2));console.log(JSON.stringify({total:products.length,withDetails:details.size,withGroups:products.filter(p=>p.groups.length).length}));

